'use client';
import { useState } from 'react';
import Link from 'next/link';
import styles from '@/app/crypto-macro/crypto-macro.module.css';
import type { Series, Snapshot } from '@/lib/crypto-macro/types';
import { macroAlignment, relationship } from '@/lib/crypto-macro/macro-alignment';
import { correlationObservation, formatMetric } from '@/lib/crypto-macro/observations';
import { pearson, pairedReturns, rebase, volatility, drawdown, leadLag } from '@/lib/crypto-macro/calculations/metrics';
import { WINDOWS } from '@/lib/crypto-macro/config';

function fmt(value: number | null, digits = 2) { return value === null ? '—' : value.toFixed(digits); }
function LineChart({ lines, labels }: { lines: number[][]; labels: string[] }) {
  const all = lines.flat(); const min = Math.min(...all), max = Math.max(...all); const width = 800, height = 220;
  const path = (values: number[]) => values.map((v, i) => `${i ? 'L' : 'M'} ${(i / Math.max(1, values.length - 1)) * width} ${height - ((v - min) / Math.max(1e-9, max - min)) * height}`).join(' ');
  return <svg className={styles.chart} viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Historical relationship chart"><line className={styles.axis} x1="0" y1="30" x2={width} y2="30"/><line className={styles.axis} x1="0" y1="110" x2={width} y2="110"/><line className={styles.axis} x1="0" y1="210" x2={width} y2="210"/>{lines.map((line, i) => <path key={labels[i]} d={path(line)} className={i % 2 ? styles.lineAlt : styles.line}/>)}</svg>;
}
function MetricCard({ series }: { series: Series }) { const last = series.points.at(-1)?.value ?? null; const first = series.points[0]?.value ?? null; const change = last !== null && first ? (last / first - 1) * 100 : null; return <div className={styles.metric}><small>{series.name}</small><strong>{last === null ? '—' : last.toLocaleString(undefined, { maximumFractionDigits: series.kind === 'price' ? 2 : 3 })}</strong><em>{series.unit} · {change === null ? 'Unavailable' : `${change >= 0 ? '+' : ''}${change.toFixed(1)}% range`}</em></div>; }

export default function Dashboard({ snapshot }: { snapshot: Snapshot }) {
  const available = snapshot.series.filter(s => s.status === 'available');
  const [aId, setAId] = useState(available[0]?.id ?? 'btc');
  const [bId, setBId] = useState(available[1]?.id ?? 'eth');
  const [window, setWindow] = useState<(typeof WINDOWS)[number]>(90);
  const a = snapshot.series.find(s => s.id === aId) ?? available[0]; const b = snapshot.series.find(s => s.id === bId) ?? available[1];
  const pair = a && b ? relationship(a, b) : null;
  const alignment = macroAlignment(snapshot.series);
  const range = available.slice(0, 4).map(s => rebase(s.points).map(p => p.value));
  const matrix = available.slice(0, 5).map(x => available.slice(0, 5).map(y => { const p = pairedReturns(x.points, y.points, x.kind === 'rate', y.kind === 'rate'); return pearson(p.a, p.b).value; }));
  return <main className={styles.main}>
    {snapshot.development && <div className={styles.statusBanner}>Development data · SYNTHETIC TEST DATA. Production never falls back to fixtures.</div>}
    <div className={styles.eyebrow}>Cross-market observatory / daily closes</div><h1 className={styles.title}>See the market relationships moving together, diverging and changing.</h1><p className={styles.subtitle}>Crypto Macro maps transparent statistical relationships across crypto, currencies and macro series. It describes what has happened; it does not predict what happens next.</p>
    <section className={styles.hero}><div className={styles.heroCard}><h2>Macro Alignment</h2><div className={styles.alignment}><span className={styles.bigNumber}>{alignment.notable} / {alignment.available}</span><span className={styles.alignmentLabel}>available relationships showing notable behaviour</span></div><p className={styles.heroNote}>Notable means at least one documented correlation threshold is met. This count uses only enabled series with 250 historical observations and enough paired returns.</p><span className={styles.refresh}>Snapshot {new Date(snapshot.asOf).toLocaleString()}</span></div><div className={styles.heroSide}>{available.slice(0, 6).map(s => <MetricCard key={s.id} series={s}/>)} </div></section>
    <div className={styles.grid}>
      <section className={`${styles.panel} ${styles.wide}`}><div className={styles.panelHeader}><h2 className={styles.panelTitle}>Relationship explorer</h2><span className={styles.panelMeta}>daily log returns · aligned dates</span></div><div className={styles.controls}><select aria-label="First series" className={styles.select} value={aId} onChange={e => setAId(e.target.value)}>{available.map(s => <option key={s.id} value={s.id}>{s.symbol} · {s.name}</option>)}</select><select aria-label="Second series" className={styles.select} value={bId} onChange={e => setBId(e.target.value)}>{available.map(s => <option key={s.id} value={s.id}>{s.symbol} · {s.name}</option>)}</select><select aria-label="Correlation window" className={styles.select} value={window} onChange={e => setWindow(Number(e.target.value) as (typeof WINDOWS)[number])}>{WINDOWS.map(w => <option key={w} value={w}>{w} observations</option>)}</select></div>{pair && a && b ? <><LineChart lines={[a.points.map(p => p.value), b.points.map(p => p.value)]} labels={[a.symbol,b.symbol]}/><div className={styles.relationship}><span><strong>{a.symbol} / {b.symbol}</strong><br/><span className={styles.muted}>{correlationObservation({ value: pair[`c${window}` as 'c30' | 'c90' | 'c180'], n: pair.n })}</span></span><span className={styles.tag}>{pair.state.label}</span></div><p className={styles.muted}>The current {window}-observation correlation is {fmt(pair[`c${window}` as 'c30' | 'c90' | 'c180'])}. Relationship history is sensitive to the selected period and does not establish causation. {pair.multiDay ? `${pair.multiDay} intervals span more than one calendar day because traditional markets do not trade every day.` : ''}</p></> : <div className={styles.empty}>Choose two available series to explore.</div>}</section>
      <section className={`${styles.panel} ${styles.narrow}`}><div className={styles.panelHeader}><h2 className={styles.panelTitle}>Notable relationships</h2><span className={styles.panelMeta}>thresholds visible</span></div>{alignment.available ? alignment.relationships.filter(r => r.notable).slice(0, 8).map(r => <div className={styles.relationship} key={r.id}><span className={styles.relName}>{r.label}<br/><span className={styles.muted}>{r.triggers.join(' · ')}</span></span><span className={styles.tag}>observed</span></div>) : <div className={styles.empty}>No eligible relationships yet. Enable licensed daily sources to populate this view.</div>}</section>
      <section className={`${styles.panel} ${styles.wide}`}><div className={styles.panelHeader}><h2 className={styles.panelTitle}>Correlation matrix</h2><span className={styles.panelMeta}>sample Pearson · aligned return observations</span></div>{matrix.length ? <div className={styles.heatmap}>{matrix.flatMap((row, i) => row.map((value, j) => <div key={`${i}-${j}`} className={styles.heat} style={{ background: value === null ? '#20313a' : value >= 0 ? `rgba(104,226,197,${Math.max(.18, Math.abs(value))})` : `rgba(246,180,90,${Math.max(.18, Math.abs(value))})` }} title={`${available[i].symbol} / ${available[j].symbol}`} >{value === null ? '—' : value.toFixed(2)}</div>))}</div> : <div className={styles.empty}>Unavailable until two licensed series have aligned data.</div>}<p className={styles.muted}>Green indicates positive association; amber indicates negative association. Colour describes the number, not a market direction.</p></section>
      <section className={`${styles.panel} ${styles.narrow}`}><div className={styles.panelHeader}><h2 className={styles.panelTitle}>Relative performance</h2><span className={styles.panelMeta}>rebased to 100</span></div>{range.length ? <LineChart lines={range} labels={available.slice(0,4).map(s=>s.symbol)}/> : <div className={styles.empty}>Unavailable: no licensed series.</div>}<p className={styles.muted}>Each line starts at 100 on the selected range. This is a comparison of historical movement, not a return forecast.</p></section>
      <section className={`${styles.panel} ${styles.narrow}`}><div className={styles.panelHeader}><h2 className={styles.panelTitle}>Volatility & drawdown</h2><span className={styles.panelMeta}>30 observations</span></div>{a ? <><p><span className={styles.muted}>{a.symbol} annualised volatility</span><br/><strong>{formatMetric(volatility(a.points, a.category === 'crypto').value === null ? null : volatility(a.points, a.category === 'crypto').value! * 100)}{volatility(a.points, a.category === 'crypto').value === null ? '' : '%'}</strong></p><p><span className={styles.muted}>Current drawdown</span><br/><strong>{formatMetric(drawdown(a.points).current === null ? null : drawdown(a.points).current! * 100)}{drawdown(a.points).current === null ? '' : '%'}</strong></p><p className={styles.muted}>Volatility uses standard deviation of daily log returns and √365 for crypto or √252 for traditional series.</p></> : <div className={styles.empty}>Unavailable.</div>}</section>
      <section className={`${styles.panel} ${styles.wide}`}><div className={styles.panelHeader}><h2 className={styles.panelTitle}>Historical lead / lag</h2><span className={styles.panelMeta}>offsets −30 to +30 observations</span></div>{pair ? <><p className={styles.heroNote}>This is a historical cross-correlation association. It is sensitive to the selected period and does not imply causation or prediction.</p><table className={styles.table}><tbody><tr><th>Strongest absolute association</th><td>{pair ? `${fmt(leadLag(pairedReturns(a.points,b.points,a.kind==='rate',b.kind==='rate').a, pairedReturns(a.points,b.points,a.kind==='rate',b.kind==='rate').b).best?.value ?? null)} at offset ${leadLag(pairedReturns(a.points,b.points,a.kind==='rate',b.kind==='rate').a, pairedReturns(a.points,b.points,a.kind==='rate',b.kind==='rate').b).best?.offset ?? '—'}` : '—'}</td></tr><tr><th>Observations</th><td>{pair.n}</td></tr></tbody></table></> : <div className={styles.empty}>Select two available series.</div>}</section>
      <section className={`${styles.panel} ${styles.narrow}`}><div className={styles.panelHeader}><h2 className={styles.panelTitle}>Data availability</h2><span className={styles.panelMeta}>source transparency</span></div>{snapshot.series.slice(0, 8).map(s => <div className={styles.relationship} key={s.id}><span className={styles.relName}>{s.symbol}<br/><span className={styles.muted}>{s.status === 'available' ? `${s.provider} · updated ${s.sourceUpdatedAt ?? 'recently'}` : s.message}</span></span><span className={s.status === 'available' ? styles.tag : styles.muted}>{s.status === 'available' ? 'live' : 'unavailable'}</span></div>)}</section>
      <section className={styles.cta}><div><h2>Want the full Macro Intelligence Suite?</h2><p>Join the VIP waitlist for deeper history, more markets, advanced alignment, alerts, watchlists, regime comparisons and the future Chart Analyzer.</p></div><Link href="/crypto-macro#waitlist">Join the VIP Waitlist</Link></section>
      <Waitlist />
    </div>
  </main>;
}
function Waitlist() { const [email,setEmail]=useState(''); const [consent,setConsent]=useState(false); const [status,setStatus]=useState(''); async function submit(e:React.FormEvent){e.preventDefault();setStatus('Joining…');try{const res=await fetch('/api/crypto-macro/waitlist',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,consent,source:'dashboard',website:''})});const data=await res.json();setStatus(data.message ?? 'Something went wrong.');if(res.ok)setEmail('')}catch{setStatus('Temporarily unavailable. Please try again later.')}} return <section id="waitlist" className={`${styles.panel} ${styles.wide}`}><h2 className={styles.panelTitle}>VIP waitlist</h2><p className={styles.heroNote}>The free dashboard stays open. Leave an email if you want to hear when the paid suite is ready.</p><form onSubmit={submit}><div className={styles.form}><input className={styles.input} type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" aria-label="Email address"/><button className={styles.button} disabled={!consent}>Join waitlist</button></div><label className={styles.consent}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Email me about the Crypto Macro VIP suite. Unsubscribe any time.</span></label><input tabIndex={-1} autoComplete="off" name="website" aria-hidden="true" style={{position:'absolute',left:'-10000px'}}/><p className={styles.muted} aria-live="polite">{status}</p></form></section> }

